const arrLang = {
    en: {
        recCourse: 'Enroll in a course',
        coursesMenu:'courses',
        aboutMenu: 'about us',
        partnersMenu: 'partners',
        reviewsMenu: 'reviews',
        contactsMenu: 'contacts',
        itCollage:'International IT College',
        bestCourses:'Best IT courses in Ukraine',
        chooseCourses:'Choose course',
        //-----------------------------------
        advantagesOfIT:'Advantages of IT',
        advantagesContent:'There are a lot of IT-employees, but nevertheless, the number of vacancies is not decreasing, which means that there is demand. Only directions change.',
        advantahesContent1:'Advantages of IT direction:',
        aboutTitle:'About us',
        aboutText:'is an educational project whose goal is to educate all comers (of any age and level of training) in relevant IT specialties. Our mission is to educate as many people as possible and give them the opportunity to get a sought-after and highly paid profession in the shortest possible time. The school represents sites, facilities, educational programs and teachers.',
        facts1:'STUDENTS GET WORK',
        facts2:'STUDENTS COME ON FRIENDS RECOMMENDATION',
        facts3:'GRADUATES FOR THE ALL TIME OF WORKING',
        facts4:'HOURS OF PRACTICE',

        devEducation:'Dev Education',
        itCollage:'International IT College',
        bestCourses:'Best IT courses in Ukraine',
        chooseCourses:'Choose course',
        innerTitleH2:'Dev Education',
        inner__suptitle:'INTERNATIONAL IT COLLEGE',
        inner__suptitle2BestIT:'Best IT courses in Ukraine',
        chooseCurs:'Сhoose course',
        course__descriptionSharp:'The course will introduce you to programming, basic concepts and concepts, lay the foundation on which the rest of the training will be based.',
        moreDetails:'More details',
        course__descriptionFE:'The course is an introduction to web development using Javascript, Html and Css.',
        course__descriptionQA:'A practical course covering all the basic concepts used in software testing. Consists of input into manual testing and the basics of automation',
        privacyPolicy:'Privacy Policy',
        addressSPB:'Karl Faberge Square, 8B, office 440 BC Golden Valley',
        addressKharkiv:'st. Donets Zakharzhevskogo, 2, building of Sberbank, floor 5',
        cityKharkiv:'Kharkiv',
        citySPB:'St. Peterburg',
        addressBaku:'Babek avenue 10E, Rusel Plaza, 7th floor',
        cityBaku:'Baku',
        addressDnipro: 'st. Svyatoslav the Brave, 12, office 201, "Citadel" Business Center',
        cityDnipro:'Dnipro',
        addressKiev:'metro Vasilkovskaya, st. Sumska, 1',
        cityKiev:'Kiev',
        ourStudents: 'Our Student',
        reviews: 'Reviews of our students',
        highSalary:'High salary',
        highSalary2:'Demand of developers',
        highSalary3:'Interesting tasks and space for creativity',
        highSalary4:'Possibility of remote work and free schedule',
        highSalary5:'Fast career growth',

    },
    ru: {
        recCourse:'Записаться на курс',
        coursesMenu:'курсы',
        aboutMenu: 'о нас',
        partnersMenu: 'партнеры',
        reviewsMenu: 'отзывы',
        contactsMenu: 'контакты',
        itCollage:'Международный IT- коледж',
        bestCourses:'Лучшие IT курсы в Украине',
        chooseCourses:'Выбрать курс',
        //-----------------------------------
        advantagesOfIT:'Преимущества IT направления',
        advantagesContent:'IT-шников очень много, но тем не менее, количество вакансий не уменьшается, значит, спрос есть. Меняются только направления.',
        advantahesContent1: 'Плюсы профессии программист:',
        aboutTitle:'О нас',
        aboutText:' – образовательный некоммерческий проект, цель которого – обучить всех желающих (любого возраста и уровня подготовки) актуальным IT специальностям. Наша миссия — обучить как можно большее количество людей и дать им возможность получить востребованную и высокооплачиваемую профессию в максимально короткий срок. Школа представляет площадки, помещения, образовательные программы и преподавателей.',
        facts1:'ТРУДОУСТРАИВАЮТСЯ ПОСЛЕ ОКОНЧАНИЯ',
        facts2:'студентов пришли по рекомендации друзей',
        facts3:'ВЫПУСКНИКОВ ЗА ВСЕ ВРЕМЯ РАБОТЫ',
        facts4:'ЧАСОВ ПРАКТИЧЕСКИХ ЗАНЯТИЙ',
        devEducation:'Dev Education',

        itCollage:'Международный IT- коледж',
        bestCourses:'Лучшие IT курсы в Украине',
        chooseCourses:'Выбрать курс',
        innerTitleH2:'Dev Education',
        inner__suptitle:'МЕЖДУНАРОДНЫЙ IT- КОЛЕДЖ',
        inner__suptitle2BestIT:'Лучшие IT курсы в Украине',
        chooseCurs:'Выбрать курс',
        course__descriptionSharp:'Курс познакомит вас с программированием, базовыми понятиями и концепциями, заложит основу, на которой будет основоватся остальная часть обучения.',
        moreDetails:'Подробнее',
        course__descriptionFE:'Курс представляет собой введение в веб-разработку с использованием Javascript, Html и Css.',
        course__descriptionQA:'Практический курс, охватывающий все основные концепции, используемые при тестировании програмного обеспеченияю. Состоит из ввода в мануальное тестирование и основ автоматизациию',
        privacyPolicy:'Политика конфиденциальности',
        addressSPB:'площадь Карла Фаберже, 8Б, офис 440 БЦ Золотая Долина',
        addressKharkiv:'ул. Донец Захаржевского, 2, здание Сбербанка, этаж 5',
        cityKharkiv:'Харьков',
        citySPB:'Санкт-Петербург',
        addressBaku: 'проспект Бабека 10E, Rusel Plaza, 7 этаж',
        cityBaku:'Баку',
        addressDnipro:'ул. Святослава Храброго, 12, офис 201, Бизнес-центр "Цитадель"',
        cityDnipro: 'Днепр',
        addressKiev: 'ст. метро Васильковская, ул. Сумская,1',
        cityKiev: 'Киев',
        ourStudents: 'Наши студенты',
        reviews: 'Отзывы наших студентов',
        highSalary:'Высокая зарплата',
        highSalary2:'Востребованность',
        highSalary3:'Интересные задачи и простор для творчества',
        highSalary4:'Возможность удаленной работы и свободный график',
        highSalary5:'Карьерный рост в своей стране и за рубежом',

    },
    ua: {
        recCourse:'Записатися на курс',
        inner__suptitle2BestIT:'Кращі IT курси в Україні',
        coursesMenu:'курси',
        aboutMenu: 'про нас',
        partnersMenu: 'партнери',
        reviewsMenu: 'відгуки',
        contactsMenu: 'контакти',
        itCollage:'Міжнародний IT- коледж',
        bestCourses:'Кращі IT курси в Україні',
        chooseCourses:'Підібрати курс',
        //----------------------------------------
        advantagesOfIT:'Переваги ІТ напрямку',
        advantagesContent:'ІТ-шників зараз дуже багато, але тим не менш, кількість вакансій не зменшується, а значить, попит є. Змінюються лиш направлення.',
        advantahesContent1:'Переваги роботи програмістом',
        aboutTitle:'Про нас',
        aboutText:'- освітній некомерційний проект, ціль якого - навчити усіх бажаючих (любого віку та рівня підготовки)актуальним ІТ спеціальностям Наша місія - навчити як можна більшу кількість людейта дати їм можливість отримати затребувану та високооплачувану професіюв максимально короткий срок. Школа представляє приміщення, освітні програми та викладачів.',
        facts1:'Працевлаштовуються посля закінчення',
        facts2:'Студенти прийшли за рекомендацією друзів',
        facts3:'Випускниківза весь час',
        facts4:'Годин практичних занять',
        devEducation:'Dev Education',
        itCollage:'Міжнародний IT- коледж',
        bestCourses:'Кращі IT курси в Україні',
        chooseCourses:'Підібрати курс',
        innerTitleH2:'Dev Education',
        inner__suptitle:'МІЖНАРОДНИЙ ІТ КОЛЕДЖ',
        chooseCurs:'Вибрати курс',
        course__descriptionSharp:'Курс познайомить вас з програмуванням, базовими поняттями і концепціями, закладе основу, на якій буде основоватся інша частина навчання.',
        moreDetails:'Докладніше',
        course__descriptionFE:'Курс являє собою введення в веб-розробку з використанням Javascript, Html і Css.',
        course__descriptionQA:'Практичний курс, що охоплює всі основні концепції, які використовуються при тестуванні програмного обеспеченіяю. Складається з введення в мануальное тестування і основ автоматізаціію.',
        privacyPolicy: 'Політика конфіденційності',
        addressSPB:'площа Карла Фаберже, 8Б, офіс 440. БЦ Золота Долина',
        addressKharkiv:'вул. Донець Захаржевського,2. Будівля Збербанку, 5 поверх',
        cityKharkiv:'Харків',
        citySPB:'Санкт-Петербург',
        addressBaku:'проспект Бабека 10Е, Русел Плаза, 7 етаж',
        cityBaku:'Баку',
        addressDnipro:'вул. Святослава Хороброго, 12. Офіс 201, Бізнес-центр "Цитадель"',
        cityDnipro:'Дніпро',
        addressKiev:'станціяметро Васильківська, вул. Сумська, 1',
        cityKiev:'Київ',
        ourStudents: 'Нашi студенти',
        reviews: 'Вiдгуки наших студентiв',
        highSalary:'Висока заробітня плата',
        highSalary2:'Попит на ринку',
        highSalary3:'Інтенсивні задачіта простір для самореалізації',
        highSalary4: 'Можливість віддаленої роботи та вільний графік',
        highSalary5:'Карьєрний зріст у своїй країні та за кордоном',
    },
};